### PR TITLE
3920 opening the menu breaks the back button

### LINKED ISSUE #3920: Opening the menu breaks the back button
## Summary

If you click to open one of the top level menu links, Enterprise, Developer, Community, etc. the back button does not work as expected.

## Process

Click one of the top menu items then hit the back button. You'll see the url change but the menu does not close.

Clicking to open and close a number of menu's then hitting the back button updates the url multiple times but the last opened menu stays active.

## Current and expected result

The menu doesn't close. It should

### PR DESCRIPTION
**Pull request by solazio**
## Done

Pressing the back button closes the menu

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Click one of the top menu items then hit the back button. You should see the url changing and the menu closing.

## Issue / Card

Fixes #3920

### CODE REVIEW

File: static/js/navigation.js [hunk 1]
```diff
@@ -34,6 +35,16 @@ navDropdowns.forEach(function(dropdown) {
   });
 });
 
+// Close the menu if browser back button is clicked
+window.addEventListener('hashchange', function(event) {
+  navDropdowns.forEach(function (dropdown) {
+    var dropdownContent = document.getElementById(dropdown.id + "-content");
```
Comment (barrymcgee) [inline static/js/navigation.js]:
```suggestion
    const dropdownContent = document.getElementById(dropdown.id + "-content");
```

**Comment by solazio** [comment]
@barrymcgee thanks. I've committed your suggestion and will merge once the checks have passed.
